apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf-check
  namespace: iperf
spec:
  selector:
    matchLabels:
      app: iperf-check
  replicas: 1
  template:
    metadata:
      labels:
        app: iperf-check
    spec:
      containers:
        - name: iperf-check
          image: quay.io/two.oes/iperf-check
          env:
          - name: URL_INTERVAL
            value: 30
          - name: IPREF_CLIENT_URI
            value: ''
          - name: IPREF_SERVER 
            value: ''
          - name: WARNING_LIMIT
            value: 5000
          - name: SERVER_PORT
            value: 5001
          - name: CRITICAL_LIMIT
            value: 3000
          - name: USE_DEBUG
            value: False
          - name: BITPERSEC_FORMAT
            value: M
          - name: OUTPUT_FORMAT
            value: log
